apiVersion: batch/v1
kind: Job
metadata:
  name: backend-test
  namespace: webapp
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: styled-charts
    app.kubernetes.io/version: '0.0.0'
    app.kubernetes.io/component: function
    app.kubernetes.io/part-of: serverless
    app.kubernetes.io/managed-by: tilt

spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-test
        image: curlimages/curl
        command: ["curl",  "-fsSL", "http://localhost:3000/api?url=https://raw.githubusercontent.com/plotly/plotly.js/master/test/image/mocks/0.json&width=400&height=400"]
      restartPolicy: Never
