version: '3.9'

x-deploy: &deploy-template
  deploy:
    mode: global

x-restart-deploy: &restart-deploy-template
  <<: *deploy-template
  deploy:
    restart_policy:
      condition: on-failure
      max_attempts: 3
      delay: 5s
      window: 120s

x-replica-deploy: &replica-deploy-template
  <<: *deploy-template
  deploy:
    mode: replicated
    replicas: 2
    update_config:
      parallelism: 2
      delay: 10s
      order: stop-first
    resources:
      limits:
        cpus: '0.5'
        memory: 1000M
      reservations:
        memory: 250M

x-logging: &logging-template
  logging:
    options:
      max-size: "100m"
      max-file: "10"

x-restart: &restart-template
  restart: unless-stopped

services:
  app:
    <<: *deploy-template
    <<: *logging-template
    <<: *restart-template
    container_name: ${APP_CONTAINER_NAME:-'styled-charts'}
    image: ${APP_IMAGE_NAME:-'styled-charts'}
    hostname: ${APP_HOST_NAME:-'styled-charts'}
    domainname: ${APP_DOMAIN_NAME:-'docker.local'}
    extra_hosts:
      - "server:127.0.0.1"
    build:
      context: './'
      dockerfile: Dockerfile
      labels:
        - "org.opencontainers.image.authors=Alexander Rogalskiy"
        - "org.opencontainers.image.vendor=Sensiblemetrics, Inc."
      args:
        IMAGE_SOURCE: "$IMAGE_SOURCE"
        IMAGE_TAG: "$IMAGE_TAG"
        VERCEL_TOKEN: "$VERCEL_TOKEN"
    secrets:
      - vercel_token
    env_file:
      - .env
    #    environment:
    #      VERCEL_TOKEN: /run/secrets/vercel_token
    volumes:
      - type: volume
        source: appvolume
        target: /usr/src/app
        volume:
          nocopy: true
      - type: bind
        source: ./data
        target: /usr/src/data
    healthcheck:
      test: [ 'CMD-SHELL', 'nc', '-vz', 'localhost', '3000' ]
      interval: 3s
      retries: 15
      start_period: 30s
    networks:
      - default
    ports:
      - '${IP_ADDRESS:-127.0.0.1}:${APP_SERVER_PORT:-3000}:3000'

  web:
    container_name: ${PROXY_APP_CONTAINER_NAME:-'proxy-styled-charts'}
    image: ${PROXY_APP_IMAGE_NAME:-'nginx'}
    hostname: ${PROXY_APP_HOST_NAME:-'proxy-styled-charts'}
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8443:443
      - 8080:80
    depends_on:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST
    networks:
      - default
      - external

networks:
  external:
    external: true
  internal:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
        - gateway: "192.168.0.1"
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  appvolume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./

secrets:
  vercel_token:
    file: ./vercel_token.txt # put vercel token to this file
