version: "3.9"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "$DOCKER_SUBNET"
#  internal:
#    driver: overlay
#    ipam:
#      driver: default
#      config:
#        - subnet: "192.168.0.0/24"
#        - gateway: "192.168.0.1"
